### ISSUE TITLE
FollowUp

### ISSUE THREAD

**Issue by inishchith** [KJSCE-Codecell/Introduction-to-programming#1]
File-name : **N-topic.md** ( n being topic number on main readme.md and  topic being topic name )

branch-name : **contrib-name**

Note : Use **syntax highlighting** wherever necessary . 

Comment below the topic on which you're working .

**Comment by cipherhacker** [comment]
variables

**Comment by nurdtechie98** [comment]
conditionals and loops

**Comment by inishchith** [comment]
I/O and Arrays/Lists

**Comment by jaykanakiya** [comment]
User defined functions

**Comment by inishchith** [comment]
is In build functions , Modules & Lambda assigned to anyone ? if anyone is  willing to please comment .

**Comment by Chaitya62** [comment]
anything missing ? @brindashar4  @shivam1708  read the docs  and proof read as well as run
