### ISSUE TITLE
Subheadings do not appear on the webpage as links in  jekyll theme 

### ISSUE THREAD

**Issue by Chaitya62** [KJSCE-Codecell/Introduction-to-programming#10]
check [this](http://kjscecodecell.com/Introduction-to-programming/python/variables.html)

**Comment by nurdtechie98** [comment]
Didn't get you

**Comment by Chaitya62** [comment]
On the left hand side there should be links for what is Variable? (change that to what is a variable as well ), Declaration,Multiple Assignments

**Comment by inishchith** [comment]
@Chaitya62 i think we should use cayman as the documents aren't lengthy to have those sidebars now .what say @nurdtechie98 ?

**Comment by nurdtechie98** [comment]
Ya it looks cool but then depends on whether we need the presentation to be formal

**Comment by Chaitya62** [comment]
Let's decide after 90% of documentation is done

**Comment by nurdtechie98** [comment]
@inishchith  try using h2(##) instead of h3(###) for those subheadings will work probably

**Comment by nurdtechie98** [comment]
@Chaitya62  @inishchith  it works added to my pr close the issue
